# Generated by Django 4.1.9 on 2024-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_database', '0003_alter_tranzakcio_datatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzakcio',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
